Fix filter in Adapt.findRelativeModel
adaptlearning/adapt_framework pull request #3033
Opened 2021-02-11 13:33 UTC by tomgreenfield

Resolves #3031.

2021-02-11 14:40 UTC, moloko commented on src/core/js/models/adaptModel.js
> +    const shouldSkip = model => {
comment with link to issue might be useful here i.e.
// https://github.com/adaptlearning/adapt_framework/issues/3031

2021-02-11 14:41 UTC, oliverfoster requested changes

2021-02-11 14:41 UTC, oliverfoster commented on src/core/js/models/adaptModel.js
> +      const isSelf = i === modelIndex;
Can I get some brackets up in here?
```suggestion
      const isSelf = (i === modelIndex);
```

2021-02-11 14:41 UTC, oliverfoster commented on src/core/js/models/adaptModel.js
> +      return typeof options.filter === 'function' && !options.filter(model);
I think I preferred your original version where `typeof options.filter === 'function'` wasn't executed at each iteration.

2021-02-11 16:49 UTC, oliverfoster commented on src/core/js/models/adaptModel.js
> +    const isFilterFunction = typeof options.filter === 'function';
```suggestion
    const isFilterFunction = (typeof options.filter === 'function');
```

2021-02-12 10:40 UTC, moloko approved these changes
code 👓

2021-02-15 16:34 UTC, oliverfoster approved these changes

2021-02-18 11:07 UTC, eleanor-heath approved these changes

2021-02-18 11:13 UTC, cahirodoherty-learningpool approved these changes
👀

2021-02-18 11:44 UTC, merged