issue/3163 New scoring api
adaptlearning/adapt_framework pull request #3172
Opened 2021-06-13 00:17 UTC by oliverfoster

2021-06-14 10:39 UTC, cahirodoherty-learningpool approved these changes
👀

2021-06-14 12:11 UTC, eleanor-heath approved these changes

2021-06-14 12:14 UTC, eleanor-heath approved these changes

2021-06-16 10:52 UTC, tomgreenfield requested changes

2021-06-16 10:52 UTC, tomgreenfield commented on src/core/js/models/itemsQuestionModel.js
> +    return scores.reverse().slice(0, this.get('_seletable')).filter(score => score > 0).reduce((maxScore, score) => (maxScore += score), 0);
Typo here and on line 134 (`seletable`).

2021-06-16 10:52 UTC, tomgreenfield commented on src/core/js/models/questionModel.js
> +      _isItemScoring: false,
Suggest `_hasItemScoring`?

2021-06-17 11:20 UTC, chrisgillison commented
Using Framework 5.13.0 as a starting point, I've changed the Framework, Assessment & MCQ files to test this. Each correct question item in the assessment has had a "_score" attribute added under "_shouldBeSelected", with values of 4 for correct & 0 for incorrect, but I'm still getting awarded 1 point per question, and maxScore value is the same as the number of questions posed. Am I missing something?

2021-06-17 11:40 UTC, oliverfoster commented
Probably:
`
"_hasItemScoring": true
`

2021-06-17 11:44 UTC, oliverfoster commented
![image](https://user-images.githubusercontent.com/7974663/122390261-b29bc200-cf69-11eb-97f6-967a6ea44029.png)

2021-06-17 11:48 UTC, chrisgillison commented
> 
> 
> ![image](https://user-images.githubusercontent.com/7974663/122390261-b29bc200-cf69-11eb-97f6-967a6ea44029.png)

Oh God! How incredibly embarrassing! Yep - works like a dream for me now!

2021-06-18 14:15 UTC, merged

2021-06-22 17:12 UTC, chrisgillison commented
Personally, I think this is a brilliant enhancement to the scoring API Ollie. Something to shout about. Sometimes there is no set of correct/incorrect answers, but rather degrees of correctness. I can think of a number instances where I could have used this in the past.

So, is adapt-contrib-matching next on your list?!! I tried to update it myself using your mods to itemsQuestionModel as a guide, but of course each item has multiple options. My efforts led to a hopelessly broken component ;D

2021-06-22 18:14 UTC, oliverfoster commented
Yup. Matching next. 

Glad you like it. It's been frustrating me for ages the lack of item specific scoring.