Fix: Pass cli variables into scripts (fixes #3365)
adaptlearning/adapt_framework pull request #3366
Opened 2023-02-20 12:32 UTC by oliverfoster

fixes #3365 

### Fix
* Add `coursedir` (and all other compliation variables) in script `options` arguments

2023-02-21 10:56 UTC, cahirodoherty-learningpool approved these changes
👀

2023-03-01 16:12 UTC, swashbuck approved these changes
👍

2023-03-08 12:57 UTC, danielghost commented on grunt/tasks/scripts.js
> +        const src = options.plugins[i];
```suggestion
      options.plugins.forEach(src => {
```

2023-03-08 13:09 UTC, danielghost requested changes
Very minor suggestion: https://github.com/adaptlearning/adapt_framework/pull/3366/files#r1129390620

2023-03-09 12:31 UTC, merged